"""MythTV Services API client."""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timezone
from typing import Any

import aiohttp

_LOGGER = logging.getLogger(__name__)

# Recording status codes as returned by the MythTV Services API.
#
# Source: MythTV v34 wiki Recording_Status page, generated by firing
# Dvr/RecStatusToString against a v34.0 backend on port 6744.
# Cross-referenced with the MythTV scheduler source (scheduler.cpp).
#
# v32+ (API v2, port 6744) returns Status as a numeric integer plus a
# separate StatusName string field.  v31 and earlier return only a numeric
# Status on port 6544.  This table covers v32/v33/v34 numeric values.
#
# NOTE on port migration:
#   v32–v33: new API on port 6744, old API on port 6544
#   v34:     port 6544 serves the new API v2; port 6744 also available
#   Future:  ports 6744 and 6550 (legacy) will eventually be removed
#
# The integration targets port 6544 (the default), which is correct for all
# supported versions.
RECORDING_STATUS: dict[int, str] = {
    # ── Negative: in-progress / terminal states (v34 authoritative) ──────
    -16: "Unknown",
    -15: "Pending",         # About to start — tuner reserved, imminent start
    -14: "Failing",         # Failing due to errors (signal lock lost, etc.)
    -13: "Unknown",
    -12: "Unknown",
    -11: "Missed",          # Not recorded — master backend was not running
    -10: "Tuning",          # Tuner is locking on to the signal  ← active
    -9:  "RecorderFailed",  # Recorder failed
    -8:  "TunerBusy",       # Tuner already in use by another recording
    -7:  "LowDiskSpace",    # Not recorded — insufficient disk space
    -6:  "ManualCancel",    # Manually cancelled
    -5:  "Missed",          # Not recorded — backend not running (duplicate)
    -4:  "Aborted",         # Recorded but aborted before completion
    -3:  "Recorded",        # Successfully recorded and still available
    -2:  "Recording",       # Currently being recorded  ← primary active state
    -1:  "WillRecord",      # Scheduled and confirmed — will record
    0:   "Unknown",
    # ── Positive: scheduler decision states (v34 authoritative) ──────────
    1:   "DontRecord",      # Rule set to "don't record"
    2:   "PreviousRecording", # Previously recorded; duplicate suppressed
    3:   "CurrentlyRecorded", # File still exists in library
    4:   "EarlierShowing",  # An earlier showing will record instead
    5:   "MaxRecordings",   # Too many recordings of this title already
    6:   "NotListed",       # Rule doesn't match any guide listings
    7:   "Conflicting",     # Higher-priority programme will record instead
    8:   "LaterShowing",    # A later showing will record instead
    9:   "Repeat",          # Repeat episode; duplicate suppressed
    10:  "Inactive",        # Recording rule is inactive
    11:  "NeverRecord",     # Marked "never record"
    12:  "RecorderOffLine", # Required recorder is off-line
    13:  "Unknown",
    14:  "Unknown",
    15:  "Unknown",
    16:  "Unknown",
}

# Statuses that mean "a tuner is actively in use right now".
#
# From the v34 wiki and scheduler source (BuildWorkList checks Recording,
# Tuning, Failing, and Pending as "active work"):
#
#   -2  → Recording  (file is being written to disk)
#   -10 → Tuning     (tuner acquiring signal lock, recording imminent)
#   -15 → Pending    (tuner reserved, about to start — counted as active
#                     by the MythTV scheduler itself)
#
# -14 (Failing) is intentionally excluded: the tuner has lost its lock
# and is not producing usable content; it should not count as recording.
ACTIVE_RECORDING_STATUSES = {-2, -10, -15}


class MythTVConnectionError(Exception):
    """Raised when connection to MythTV backend fails."""


class MythTVAPI:
    """Async client for the MythTV Services API."""

    def __init__(
        self,
        host: str,
        port: int = 6544,
        session: aiohttp.ClientSession | None = None,
        username: str | None = None,
        password: str | None = None,
    ) -> None:
        self.host = host
        self.port = port
        self._base_url = f"http://{host}:{port}"
        self._session = session
        self._auth = (
            aiohttp.BasicAuth(username, password)
            if username and password
            else None
        )
        self._owns_session = session is None

    async def _get_session(self) -> aiohttp.ClientSession:
        if self._session is None or self._session.closed:
            self._session = aiohttp.ClientSession(auth=self._auth)
        return self._session

    async def close(self) -> None:
        if self._owns_session and self._session and not self._session.closed:
            await self._session.close()

    async def _get(self, endpoint: str, params: dict | None = None) -> dict:
        session = await self._get_session()
        url = f"{self._base_url}/{endpoint}"
        try:
            async with session.get(
                url,
                params=params,
                timeout=aiohttp.ClientTimeout(total=15),
                headers={"Accept": "application/json"},
            ) as resp:
                if resp.status == 200:
                    return await resp.json(content_type=None)
                raise MythTVConnectionError(f"HTTP {resp.status} from {url}")
        except aiohttp.ClientConnectorError as err:
            raise MythTVConnectionError(
                f"Cannot connect to MythTV at {self._base_url}: {err}"
            ) from err
        except asyncio.TimeoutError as err:
            raise MythTVConnectionError(
                f"Timeout connecting to MythTV at {self._base_url}"
            ) from err

    # ── Myth service ──────────────────────────────────────────────────────────

    async def get_hostname(self) -> str:
        data = await self._get("Myth/GetHostName")
        return data.get("String", "")

    async def get_backend_info(self) -> dict:
        return await self._get("Myth/GetBackendInfo")

    async def get_connection_info(self) -> dict:
        return await self._get("Myth/GetConnectionInfo")

    async def get_storage_group_dirs(
        self, group_name: str | None = None
    ) -> dict:
        """Return storage group directory info via Myth/GetStorageGroupDirs.

        This is the correct endpoint for per-directory free-space data
        (fields: GroupName, HostName, DirName, DirRead, DirWrite, KiBFree).
        Each entry in StorageGroupDirList → StorageGroupDirs is one directory.
        """
        params: dict[str, Any] = {}
        if group_name:
            params["GroupName"] = group_name
        return await self._get("Myth/GetStorageGroupDirs", params or None)

    # ── Status service ────────────────────────────────────────────────────────

    async def get_backend_status(self) -> dict:
        return await self._get("Status/GetBackendStatus")

    # ── DVR service ───────────────────────────────────────────────────────────

    async def get_recorded_list(
        self,
        count: int = 20,
        start_index: int = 0,
        descending: bool = True,
        rec_group: str | None = None,
        ignore_deleted: bool = True,
        ignore_live_tv: bool = True,
    ) -> dict:
        params: dict[str, Any] = {
            "Count": count,
            "StartIndex": start_index,
            "Descending": "true" if descending else "false",
        }
        if rec_group:
            params["RecGroup"] = rec_group
        # FIX: IgnoreDeleted and IgnoreLiveTV were introduced in v32.
        # On v28–v31 backends these parameters are silently ignored, so it is
        # safe to always send them — but they only take effect on v32+.
        params["IgnoreDeleted"] = "true" if ignore_deleted else "false"
        params["IgnoreLiveTV"] = "true" if ignore_live_tv else "false"
        return await self._get("Dvr/GetRecordedList", params)

    async def get_upcoming_list(
        self,
        count: int = 20,
        start_index: int = 0,
        show_all: bool = False,
    ) -> dict:
        params: dict[str, Any] = {
            "Count": count,
            "StartIndex": start_index,
            "ShowAll": "true" if show_all else "false",
        }
        return await self._get("Dvr/GetUpcomingList", params)

    async def get_encoder_list(self) -> dict:
        return await self._get("Dvr/GetEncoderList")

    async def get_record_schedule_list(self) -> dict:
        return await self._get("Dvr/GetRecordScheduleList")

    async def get_conflict_list(self) -> dict:
        return await self._get("Dvr/GetConflictList")

    async def get_expiring_list(self, count: int = 10) -> dict:
        return await self._get("Dvr/GetExpiringList", {"Count": count})

    async def get_title_info_list(self) -> dict:
        return await self._get("Dvr/GetTitleInfoList")

    # ── Channel service ───────────────────────────────────────────────────────

    async def get_channel_info_list(self, only_visible: bool = True) -> dict:
        return await self._get(
            "Channel/GetChannelInfoList",
            {"OnlyVisible": "true" if only_visible else "false"},
        )

    # ── Helpers ───────────────────────────────────────────────────────────────

    async def test_connection(self) -> bool:
        try:
            await self.get_hostname()
            return True
        except MythTVConnectionError:
            return False

    def get_currently_recording(self, upcoming_programs: list[dict]) -> list[dict]:
        """Filter upcoming programmes to those currently being recorded/tuned.

        Uses ACTIVE_RECORDING_STATUSES which correctly identifies:
          -2  (Recording) — tuner is writing content to disk
          -10 (Tuning)    — tuner is acquiring signal lock
          -15 (Pending)   — tuner reserved, start imminent

        On v32+ backends a StatusName string field is also present alongside
        the numeric Status.  We handle both forms for robustness.
        """
        result = []
        for prog in upcoming_programs:
            raw = prog.get("Recording", {}).get("Status")
            if raw is None:
                continue
            # v32+ may return the string name; try numeric first.
            try:
                code = int(raw)
                if code in ACTIVE_RECORDING_STATUSES:
                    result.append(prog)
            except (ValueError, TypeError):
                # String form: compare against the label table.
                label = str(raw)
                active_labels = {
                    RECORDING_STATUS[c] for c in ACTIVE_RECORDING_STATUSES
                }
                if label in active_labels:
                    result.append(prog)
        return result

    @staticmethod
    def parse_utc(ts: str | None) -> datetime | None:
        if not ts:
            return None
        for fmt in ("%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S"):
            try:
                return datetime.strptime(ts, fmt).replace(tzinfo=timezone.utc)
            except ValueError:
                continue
        return None

    @staticmethod
    def rec_status_label(code: int | str) -> str:
        try:
            return RECORDING_STATUS.get(int(code), f"Status({code})")
        except (ValueError, TypeError):
            return str(code)
